### ISSUE TITLE
[Bug]: Login: No identity model found

### ISSUE THREAD

**Issue by emiltsang-flow** [OneSignal/react-onesignal#140]
### What happened?

"onesignal-vue": "^2.0.1"
OSModelStore.js:32 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'modelId')
    at Ji.subscribeUpdateListener (OSModelStore.js:32:41)
    at Ji.add (OSModelStore.js:16:14)
    at en.add (CoreModuleDirector.js:106:32)
    at tn.<anonymous> (LoginManager.js:113:9)
    at Generator.next (<anonymous>)
    at r (tslib.es6.js:118:58)

When I try to call the this.$OneSignal.login(EXTERNAL_ID), I got this error.

### What browsers are you seeing the problem on?

Chrome (Chromium)

### What operating system are you running?

macOS 14.1

### Steps to reproduce?

```Markdown
1. Install "onesignal-vue": "^2.0.1"
2. Run the app
3. invoke this.$OneSignal.login(EXTERNAL_ID)
4. console error Cannot read properties of undefined (reading 'modelId')
```

### What did you expect to happen?

Able to set the external id to one signal user

### Relevant log output

```Shell
OSModelStore.js:32 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'modelId')
    at Ji.subscribeUpdateListener (OSModelStore.js:32:41)
    at Ji.add (OSModelStore.js:16:14)
    at en.add (CoreModuleDirector.js:106:32)
    at tn.<anonymous> (LoginManager.js:113:9)
    at Generator.next (<anonymous>)
    at r (tslib.es6.js:118:58)
```

**Comment by jkasten2** [comment]
Thanks for reporting, we are able to reproduce this issue, but only after `OneSignal.logout()` is called. It happens if a push subscription has not been created yet. We will look making a fix for this scenario.

**Comment by jkasten2** [comment]
This has been fixed in this release:
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/160203

This update is automatic, the JS library this depends on always points the latest production WebSDK on cdn.onesignal.com.
